### ISSUE TITLE
flathub update after march 27 results in all UI characters being unreadable (squares)

### ISSUE THREAD

**Issue by castedo** [flathub/org.gnome.Rhythmbox3#66]
After updating the Rhythmbox flatpak in early April all of the characters in the Rhythmbox UI are unreadable, mostly appear as squares plus a few strange characters.

Rolling back to commit 5b28037f429eb6e7ff373cbb91b82a7bc7f271045af2b81f8ece515e86603ddd from 2022-11-15 fixes the problem. Reinstalling to the latest commit from 2023-03-27 did not fix the problem.

```
[castedo@moon ~]$ flatpak remote-info flathub org.gnome.Rhythmbox3 --log
        ID: org.gnome.Rhythmbox3
       Ref: app/org.gnome.Rhythmbox3/x86_64/stable
      Arch: x86_64
    Branch: stable
Collection: org.flathub.Stable
  Download: 6.1 MB
 Installed: 21.8 MB
   Runtime: org.gnome.Platform/x86_64/44
       Sdk: org.gnome.Sdk/x86_64/44

    Commit: 5ba5778b8a7ff12f56ba72de5d91b59dae3875f6dac4322a090445c4ebc09c41
    Parent: 5b28037f429eb6e7ff373cbb91b82a7bc7f271045af2b81f8ece515e86603ddd
   Subject: Update uchardet to 0.0.8 (9f8b5475)
      Date: 2023-03-27 11:57:48 +0000
   History: 

    Commit: 5b28037f429eb6e7ff373cbb91b82a7bc7f271045af2b81f8ece515e86603ddd
   Subject: Remove host DConf access (8fc7d9b8)
      Date: 2022-11-15 12:18:26 +0000

...
```

This is running flatpak on RHEL 9.1.

```
[castedo@moon ~]$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="9.1 (Plow)"
ID="rhel"
...
```
